### ISSUE TITLE
Implimentation code?

### ISSUE THREAD

**Issue by zobeirraisi** [wangyuxin87/ContourNet#1]
Thanks for your excellent work, when the code will be released?

**Comment by wangyuxin87** [comment]
Thanks for your attention to our work, the code has been released.

**Comment by wangyuxin87** [comment]
Thanks for your attention to our work, the code has been released.

**Comment by zobeirraisi** [comment]
Is it possible to upload the models somewhere else instead of Baidu? it is hard to download it. :)

**Comment by wangyuxin87** [comment]
Thanks for your suggestion, we will upload the models on Drive soon.
