### ISSUE TITLE
About alphashape algorithm and NMS

### ISSUE THREAD

**Issue by DREAMXFAR** [wangyuxin87/ContourNet#11]
Hello, I have read your paper and I think it is a quite good job. However, I met some problems when doing NMS and alphashape. 
As far as I know, alphashape algorithm relys on the setting of alpha and the density of the points. What's more, the number of points is not steable after NMS. I  finds that I sometimes get a better result if I don't use NMS.

So  how do you find suitable parameters in Alphashape algorithm? And  I want to know why NMS is necessarry,  will NMS bring some problems?

Thank you very much~

**Comment by wangyuxin87** [comment]
Thanks for your attention. It seems that you meet this problem when using Alpha-Shape method to represent curved text. We firstly set a large value to the parameter in Alpha-Shape to guarantee a more complete region representation and then use some tricks to refine the region based on the contour points. In addition, inspired by some key-point detection tasks, we use NMS to find the extreme points in the contour region and we find it works well in our experiments. 
I hope this can help you.

**Comment by DREAMXFAR** [comment]
Thank you for your answer. 
I am still very interested in how to refine the region. I will appreciated it if you can give some further details about the tricks you used. Do you find a different alpha for every image, or just try to find an alpha that suitable for all test images?

**Comment by wangyuxin87** [comment]
I am sorry that we do not plan to released these tricks. We just set a fixed alpha for all images.
