### ISSUE TITLE
请问bo.json中写入的是什么

### ISSUE THREAD

**Issue by qiaolegeke** [wangyuxin87/ContourNet#12]
我训自己做的数据集，请问bbox.json和bo.json分别写入的是什么

我的bo.json中是空的

然后bbox.json中写的是检测到的框的话，数量我没对应上啊
我想得到图片中每个检测区域的score

**Comment by qiaolegeke** [comment]
然后bbox.json中写的是检测到的框的话，数量我没对应上啊

**Comment by qiaolegeke** [comment]
我想得到图片中每个检测区域的score

**Comment by wangyuxin87** [comment]
你好，对于除了ic15以外的数据集我们没有生成bo.json，详见[此处](https://github.com/wangyuxin87/ContourNet/blob/bc7272dda4a8926838a72c795cc44abe05ef0697/maskrcnn_benchmark/data/datasets/evaluation/word/word_eval.py#L446)。另外，word_eval.py中[line428](https://github.com/wangyuxin87/ContourNet/blob/bc7272dda4a8926838a72c795cc44abe05ef0697/maskrcnn_benchmark/data/datasets/evaluation/word/word_eval.py#L428)可以获得score。

**Comment by qiaolegeke** [comment]
谢谢分享，我仔细看一下代码，期待分享total text的处理
