### ISSUE TITLE
Specify a python version

### ISSUE THREAD

**Issue by sergiev** [wangyuxin87/ContourNet#2]
Because now there's a conflict due to installation of the latest python by default.
```
Specifications:

  - pytorch=1.0 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
  - torchvision=0.2 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

```

**Comment by wangyuxin87** [comment]
We recommend you to use Anaconda [BaiduYun Link](https://pan.baidu.com/s/1_J9INU-UpiT43qormibAuw)(passward:1y3v) or [Geogle Drive](https://drive.google.com/file/d/1H64lTpR3xzlSRfUxfZa4dOhAYZJcO7RU/view?usp=sharing) to manage your libraries.
And the python=3.7 is used in our enviroment.

**Comment by sergiev** [comment]
@wangyuxin87 seems

**Comment by wangyuxin87** [comment]
Yes, only python 2.7 exists in our proposed Anaconda, and you will get python with version>3.7 
when you follow our installation steps .
```bash
  conda create --name ContourNet
  conda activate ContourNet
  conda install ipython
```

**Comment by sergiev** [comment]
Yep, but with python 3.8 everything fails to build due to conflict described in first message.

**Comment by wangyuxin87** [comment]
When you type following instruction, it will automatically fix your mentioned problem.
```bash
  conda install pytorch=1.0 torchvision=0.2 cudatoolkit=9.0 -c pytorch
```
which is shown in following figure:
![image](https://user-images.githubusercontent.com/33711415/82223845-c97e7800-9955-11ea-983e-697036b2343f.png)
