### ISSUE TITLE
你好，ic15 测试完成后bash test_contour.sh出现“TypeError: 'NoneType' object is not subscriptable”的问题

### ISSUE THREAD

**Issue by Joneo** [wangyuxin87/ContourNet#22]

**Comment by Joneo** [comment]
![1608715815(1)](https://user-images.githubusercontent.com/49708414/102981855-8f590280-4544-11eb-8a09-cb2d92fa288f.jpg)

**Comment by wangyuxin87** [comment]
Set the path in [this line](https://github.com/wangyuxin87/ContourNet/blob/bc7272dda4a8926838a72c795cc44abe05ef0697/maskrcnn_benchmark/data/datasets/evaluation/word/word_eval.py#L471)

**Comment by Joneo** [comment]
谢谢，加上路径以后但还是会出现一样的问题

**Comment by Joneo** [comment]
![Uploading 1608718454(1).jpg…]()

**Comment by Joneo** [comment]
![Uploading 1608718454(1).jpg…]()

**Comment by Joneo** [comment]
![1608718454(1)](https://user-images.githubusercontent.com/49708414/102986654-21b0d480-454c-11eb-89c9-8368d53304d3.jpg)

**Comment by zaghdoud2019** [comment]
> Set the path in [this line](https://github.com/wangyuxin87/ContourNet/blob/bc7272dda4a8926838a72c795cc44abe05ef0697/maskrcnn_benchmark/data/datasets/evaluation/word/word_eval.py#L471)

still same problem
