### ISSUE TITLE
Help required for a dataset of rectangular texts

### ISSUE THREAD

**Issue by abdur75648** [wangyuxin87/ContourNet#34]
Hi, @wangyuxin87 Thank you for this great work! I need help from you.
Actually, I want to run your model on a simple dataset of horizontal rectangular texts. (In annotations, 4 corners of rectangles are given).
Can you please tell me what edits in which scripts are required?

Thanks in advance

**Comment by wangyuxin87** [comment]
[This answer](https://github.com/wangyuxin87/ContourNet/issues/9) may help you

**Comment by abdur75648** [comment]
Thanks
It was helpful
