### ISSUE TITLE
ic15测试进行到一半时报错

### ISSUE THREAD

**Issue by shine-lcy** [wangyuxin87/ContourNet#5]
进行到第7/500张时，出现报错
```
1%|█▎                                                                                             | 7/500 [00:01<01:42,  4.83it/s]

......

File "/home/licaiyuan/ocr/ContourNet/maskrcnn_benchmark/data/datasets/word_dataset.py", line 98, in __getitem__
    target = target.clip_to_image(remove_empty=True)
  File "/home/licaiyuan/ocr/ContourNet/maskrcnn_benchmark/structures/bounding_box.py", line 228, in clip_to_image
    return self[keep]
  File "/home/licaiyuan/ocr/ContourNet/maskrcnn_benchmark/structures/bounding_box.py", line 213, in __getitem__
    bbox.add_field(k, v[item])
  File "/home/licaiyuan/ocr/ContourNet/maskrcnn_benchmark/structures/segmentation_mask.py", line 514, in __getitem__
    selected_instances = self.instances.__getitem__(item)
  File "/home/licaiyuan/ocr/ContourNet/maskrcnn_benchmark/structures/segmentation_mask.py", line 423, in __getitem__
    selected_polygons.append(self.polygons[i])
IndexError: list index out of range
```
检查了一下ic15_test.json，id=7的图只有一个annotation，而1-6的几张图都有多个annotation，不知道是不是由这个引起的某种边界问题。

**Comment by wangyuxin87** [comment]
请问是否有按照我们的设置配置环境？

**Comment by shine-lcy** [comment]
python3.6+cuda10 其他应该一致

**Comment by wangyuxin87** [comment]
在测试过程不需要进行label的读取，或许你可以在你的代码中注释掉这部分。
另外建议使用我们提供的anaconda进行环境配置，针对该代码我们没有在别的环境上进行过实验。

**Comment by shine-lcy** [comment]
魔改了一天终于跑出来了.. 86.5 有些配置不同 差异可以接受 谢谢大佬开源
顺便小催total_text和ctw1500的相关内容~毕竟paper是force到Arbitrary-shape的~ 再次感谢

**Comment by wangyuxin87** [comment]
谢谢关注，最近确实比较忙，曲形文字部分的内容会在开会前进行更新。

**Comment by Shualite** [comment]
> 魔改了一天终于跑出来了.. 86.5 有些配置不同 差异可以接受 谢谢大佬开源
> 顺便小催total_text和ctw1500的相关内容~毕竟paper是force到Arbitrary-shape的~ 再次感谢

请教一下，怎么魔改的？我遇到了同样的问题，感谢！

**Comment by Enki08** [comment]
> 魔改了一天终于跑出来了.. 86.5 有些配置不同 差异可以接受 谢谢大佬开源
> 顺便小催total_text和ctw1500的相关内容~毕竟paper是force到Arbitrary-shape的~ 再次感谢

我也遇到了同样的问题，请教一下是怎么修改的，感谢！

**Comment by Enki08** [comment]
> > 魔改了一天终于跑出来了.. 86.5 有些配置不同 差异可以接受 谢谢大佬开源
> > 顺便小催total_text和ctw1500的相关内容~毕竟paper是force到Arbitrary-shape的~ 再次感谢
> 
> 请教一下，怎么魔改的？我遇到了同样的问题，感谢！

请问你解决了吗？

**Comment by 01Chen** [comment]
> 魔改了一天终于跑出来了.. 86.5 有些配置不同 差异可以接受 谢谢大佬开源
> 顺便小催total_text和ctw1500的相关内容~毕竟paper是force到Arbitrary-shape的~ 再次感谢

同问是怎么改的，配置应该都是一样的，也碰到了这个问题
