### ISSUE TITLE
Is there any option in config to visualise the detection results?

### ISSUE THREAD

**Issue by Dawdleryang** [wangyuxin87/ContourNet#6]
Thank you for the code sharing. Wondering if we can visualise the detection results for a better debugging purpose? Thank you very much.

**Comment by wangyuxin87** [comment]
Thanks for your suggestion. this part will be considered in the latest version, which will be finished in this week. Or you can add your own code for visualization in word_eval.py.

**Comment by wangyuxin87** [comment]
This part has been finished, you can control the hyper-parameter ' Test_Visual' in r50_baseline.yaml for visualization.

**Comment by Dawdleryang** [comment]
Thank you very much.
