### ISSUE TITLE
Train with my own dataset?

### ISSUE THREAD

**Issue by linkworb** [wangyuxin87/ContourNet#7]
Can you tell me how to convert a dataset with only location annotations into COCO format?
I want to train with my own dataset, but I don't konw how to convert it into COCO format.

**Comment by He-haitao** [comment]
Do you install ContourNet under torch 1.0, cudatoolkit 9.0?
I met install problems with torch 1.5 cuda 10.0. 
When i run test_contour_net, it leads to many import problems about xx not exists.
![image](https://user-images.githubusercontent.com/41290343/88033329-d300a800-cb71-11ea-95ec-f7280dbd4e2a.png)

**Comment by wangyuxin87** [comment]
We upload a code to generate coco formate file from txt, which is avaliable at [this link](https://drive.google.com/file/d/1ABFPk8oFN8fYFj2aPkzM7kH7OpXZKe9W/view?usp=sharing).
