### ISSUE TITLE
coco格式的标注文件中的keypoints字段

### ISSUE THREAD

**Issue by dedety2** [wangyuxin87/ContourNet#9]
请问一下keypoints字段是否必要，在从原始标注文件（如icdar15）转到coco格式时，应该如何得到，希望得到一点指导。谢谢大佬。

**Comment by wangyuxin87** [comment]
‘segmentation’ 和 'bbox'为必要字段，我们给出了从txt向coco格式转换的代码[Link](https://github.com/wangyuxin87/ContourNet/issues/7)

**Comment by dedety2** [comment]
> ‘segmentation’ 和 'bbox'为必要字段，我们给出了从txt向coco格式转换的代码[Link](https://github.com/wangyuxin87/ContourNet/issues/7)

明白了，谢谢大佬
